channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=24.0
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.2.1
  - dataclasses==0.6
  - numpy==1.23.3
  - packaging==20.9
  - psutil==5.9.8
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
